#!/bin/bash

# Font Awesome icons for different devices
ANALOG_MIC_SYMBOL=""   # Analog Microphone
DIGITAL_MIC_SYMBOL=""   # Digital Microphone
DMIC_SYMBOL=""          # DMIC
DMIC_16K_SYMBOL=""      # DMIC16kHz (using the same as DMIC for simplicity)
USB_AUDIO_SYMBOL=""      # USB Audio

# General settings
SIZE="10"
ON_COLOR="#ffcc33"  # Color when the mic is on
OFF_COLOR="#333333"  # Color when the mic is off

# Device detection
DEVICE_STATUS=()
DEVICE_ICONS=()

# List of devices and their corresponding icons
declare -A devices
devices["/dev/snd/pcmC1D0c"]=$ANALOG_MIC_SYMBOL       # HDA Analog
devices["/dev/snd/pcmC1D1c"]=$DIGITAL_MIC_SYMBOL      # HDA Digital
devices["/dev/snd/pcmC1D6c"]=$DMIC_SYMBOL             # DMIC
devices["/dev/snd/pcmC1D7c"]=$DMIC_16K_SYMBOL         # DMIC16kHz
devices["/dev/snd/pcmC2D0c"]=$USB_AUDIO_SYMBOL         # USB Audio

# Check each microphone device
for device in "${!devices[@]}"; do
    if [[ -e "$device" ]]; then
        if [[ "$(fuser "$device" 2>/dev/null)" != "" ]]; then
            # Device is in use
            status="ON"
        else
            # Device is not in use
            status="OFF"
        fi

        # Add the icon and status to arrays
        DEVICE_STATUS+=("$status")
        DEVICE_ICONS+=("${devices[$device]}")
    fi
done

# Output the icons and statuses
output=""
for i in "${!DEVICE_STATUS[@]}"; do
    color=$OFF_COLOR
    if [[ "${DEVICE_STATUS[$i]}" == "ON" ]]; then
        color=$ON_COLOR
    fi
    output+="<span font='Hack Nerd Font Mono' size='${SIZE}' color='${color}'>${DEVICE_ICONS[$i]}</span> "
done

# Print final output
echo -e "$output"
