# Catppuccin Mocha flavor for Yazi

[flavor]
use = ""

# : Manager {{{

[manager]
cwd = { fg = "#94e2d5" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f9e2af", italic = true, underline = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#89b4fa", bg = "#89b4fa" }
marker_selected = { fg = "#f9e2af", bg = "#f9e2af" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#f9e2af" }

# Border
border_symbol = "│"
border_style  = { fg = "#7f849c" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-mocha.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#313244", bg = "#313244" }

# Mode
mode_normal = { bg = "#89b4fa", fg = "#1e1e2e", bold = true }
mode_select = { bg = "#a6e3a1", fg = "#1e1e2e", bold = true }
mode_unset  = { bg = "#f2cdcd", fg = "#1e1e2e", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#89b4fa" }
progress_error  = { fg = "#f38ba8" }

# Permissions
permissions_t = { fg = "#a6e3a1" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#89dceb" }
permissions_s = { fg = "#7f849c" }

# : }}}


# : Select {{{

[select]
border   = { fg = "#89b4fa" }
active   = { fg = "#f5c2e7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#89b4fa" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "#89b4fa" }
active   = { reversed = true }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#89b4fa" }
title   = {}
hovered = { fg = "#f5c2e7", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#181825" }
cand            = { fg = "#89dceb" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Filetype {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#89dceb" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f9e2af" },

	# Archives
	{ mime = "application/*zip", fg = "#f5c2e7" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5c2e7" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a6e3a1" },

	# Fallback
	{ name = "*", fg = "#cdd6f4" },
	{ name = "*/", fg = "#89b4fa" }
]

# : }}}
