# ===============================
# Starship Prompt — Nord Lightened Dark
# ===============================

format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$golang\
$jobs\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

# -------------------------------
# Directory
# -------------------------------
[directory]
style = "bold fg:#81A1C1"  # Nord14 green
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# -------------------------------
# Git Branch
# -------------------------------
[git_branch]
symbol = " "
style = "fg:#8FBCBB"  # Nord7 aqua
format = "[on](fg:#D8DEE9) [$symbol$branch ]($style)"

# -------------------------------
# Git Status
# -------------------------------
[git_status]
style = "fg:#A3BE8C"  # Nord14 green
format = "([$all_status$ahead_behind]($style) )"

# -------------------------------
# Programming Languages
# -------------------------------
[python]
symbol = " "
style = "fg:#EBCB8B"  # Nord13 yellow
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ""

[lua]
symbol = " "
style = "fg:#B48EAD"  # Nord15 purple

[golang]
symbol = " "
style = "fg:#88C0D0"  # Nord8 teal-blue
format = "[${symbol}(${version} )]($style)"
version_format = "v${raw}"

[package]
symbol = "󰏗 "
style = "fg:#D08770"  # Nord12 orange

# -------------------------------
# Command Duration
# -------------------------------
[cmd_duration]
min_time = 500
style = "fg:#81A1C1"  # Nord9 muted blue
format = "[$duration]($style)"

# -------------------------------
# Docker Context
# -------------------------------
[docker_context]
symbol = " "
style = "fg:#88C0D0"  # Nord8 teal
format = "[$symbol]($style) $path"

# -------------------------------
# Jobs (optional, muted accent)
# -------------------------------
[jobs]
symbol = "⚙️ "
style = "fg:#B48EAD"  # Nord15 purple
