# ===============================
# Starship Prompt — Nord Lightened Dark
# ===============================

format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$golang\
$jobs\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "bold fg:#81A1C1"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "fg:#88C0D0"
format = "[on](fg:#D8DEE9) [$symbol$branch ]($style)"

[git_status]
style = "fg:#EBCB8B"
format = "([$all_status$ahead_behind]($style) )"

[python]
symbol = " "
style = "fg:#EBCB8B"
format = '[${symbol}${pyenv_prefix} (${version} )(\($virtualenv\) )]($style)'

[lua]
symbol = " "
style = "fg:#BF616A"

[golang]
symbol = " "
style = "fg:#81A1C1"
format = "[${symbol}(${version} )]($style)"

[package]
symbol = "󰏗 "
style = "fg:#D08770"

[cmd_duration]
min_time = 500
style = "fg:#5E81AC"
format = "[$duration]($style)"

[docker_context]
symbol = " "
style = "fg:#8FBCBB"
format = "[$symbol]($style) $path"

[jobs]
symbol = "⚙️ "
style = "fg:#BF616A"
