# ===============================
# Starship Prompt — Everforest Dark Hard
# ===============================

format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$golang\
$jobs\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

# -------------------------------
# Directory
# -------------------------------
[directory]
style = "bold fg:#a7c080"  # soft green
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# -------------------------------
# Git Branch
# -------------------------------
[git_branch]
symbol = " "
style = "fg:#83c092"  # aqua green
format = "[on](fg:#d3c6aa) [$symbol$branch ]($style)"

# -------------------------------
# Git Status
# -------------------------------
[git_status]
style = "fg:#a7c080"
format = "([$all_status$ahead_behind]($style) )"

# -------------------------------
# Programming Languages
# -------------------------------
[python]
symbol = " "
style = "fg:#dbbc7f"  # warm yellow
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ""

[lua]
symbol = " "
style = "fg:#d699b6"  # soft magenta

[golang]
symbol = " "
style = "fg:#7fbbb3"  # teal blue-green
format = "[${symbol}(${version} )]($style)"
version_format = "v${raw}"

[package]
symbol = "󰏗 "
style = "fg:#e69875"  # warm orange

# -------------------------------
# Command Duration
# -------------------------------
[cmd_duration]
min_time = 500
style = "fg:#859289"  # muted gray-green
format = "[$duration]($style)"

# -------------------------------
# Docker Context
# -------------------------------
[docker_context]
symbol = " "
style = "fg:#7fbbb3"  # teal
format = "[$symbol]($style) $path"

# -------------------------------
# Jobs (optional, muted accent)
# -------------------------------
[jobs]
symbol = "⚙️ "
style = "fg:#d699b6"
